version: '3'

services:
  api:
    # image: api
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
    environment:
      - DB_HOST=db
      - DEV=true
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecret
    ports:
      - 5001:5432
    #volumes:
    #  - /var/lib/postgresql/data

